version: 2

jobs:
  build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker:
            version: 20.10.14
      - run:
          name: Build docker image
          command: docker build -t oc_projet13:$CIRCLE_SHA1 .

  push_container:
    docker:
      - image: docker:stable

    steps:
      - checkout
      - run:
          name: Log in DockerHub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Push container to DockerHub
          command: |
            docker tag oc_projet13:$CIRCLE_SHA1 $DOCKERHUB_USERNAME/oc_projet13:$CIRCLE_SHA1
            docker push $DOCKERHUB_USERNAME/oc_projet13:$CIRCLE_SHA1
  test:
    docker:
      - image: oc_projet13:$CIRCLE_SHA1
    steps:
      - checkout
      - run:
          name: Run tests
          command: pytest

workflows:
  version: 2
  build_test_push:
    jobs:
      - build
      - test:
          requires:
            - build
      - push_container:
          requires:
            - test
          filters:
            branches:
              only: master
