version: 2

jobs:
  test:
    docker:
      - image: cimg/python:3.10

    working_directory: ~/project13
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Linting
          command: |
            . venv/bin/activate
            flake8 ./ --output-file flake8_reports --ignore=F401
      - store_artifacts:
          path: flake8_reports
          destination: flake8_reports

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest

  build_and_push:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker:
            version: 20.10.14

      - run:
          name: Log in DockerHub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Build docker image
          command: |
            docker build -t $DOCKERHUB_USERNAME/oc_projet13:$CIRCLE_SHA1 .

      - run:
          name: Push container to DockerHub
          command: |
            docker push $DOCKERHUB_USERNAME/oc_projet13:$CIRCLE_SHA1

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build_and_push:
          requires:
            - test
          filters:
            branches:
              only: master
