version: 2

jobs:
  test:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Linting
          command: |
            . venv/bin/activate
            flake8
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest

  build_and_push:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker:
            version: 20.10.14

      - run:
          name: Log in DockerHub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Build docker image
          command: |
            docker build -t $DOCKERHUB_USERNAME/oc_projet13:$CIRCLE_SHA1 .

      - run:
          name: Push container to DockerHub
          command: |
            docker push $DOCKERHUB_USERNAME/oc_projet13:$CIRCLE_SHA1

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build_and_push:
          requires:
            - test
          filters:
            branches:
              only: master
