version: 2

jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install


  test:
    docker:
      - image: arnadu/test_django_p13_push:latest
    working_directory: /app
    steps:
      - checkout
#      - run: pip install -r requirements.txt
      - run: pytest

workflows:
  version: 2
  test_the_application:
    jobs:
      - test